//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFacebookApp.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyFacebookApp.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ArrayOfHitechKeyWord xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;HitechKeyWord&gt;
        ///    &lt;m_KeyWord&gt;app&lt;/m_KeyWord&gt;
        ///  &lt;/HitechKeyWord&gt;
        ///  &lt;HitechKeyWord&gt;
        ///    &lt;m_KeyWord&gt;communications&lt;/m_KeyWord&gt;
        ///  &lt;/HitechKeyWord&gt;
        ///  &lt;HitechKeyWord&gt;
        ///    &lt;m_KeyWord&gt;computer&lt;/m_KeyWord&gt;
        ///  &lt;/HitechKeyWord&gt;
        ///  &lt;HitechKeyWord&gt;
        ///    &lt;m_KeyWord&gt;cyber&lt;/m_KeyWord&gt;
        ///  &lt;/HitechKeyWord&gt;
        ///  &lt;HitechKeyWord&gt;
        ///    &lt;m_KeyWord&gt;develop&lt;/m_KeyWord&gt;
        ///  &lt;/Hitec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hitechKeyWords {
            get {
                return ResourceManager.GetString("hitechKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ArrayOfWorkPlace xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;WorkPlace&gt;
        ///    &lt;m_Name&gt;012 Smile&lt;/m_Name&gt;
        ///  &lt;/WorkPlace&gt;
        ///  &lt;WorkPlace&gt;
        ///    &lt;m_Name&gt;013 Netvision&lt;/m_Name&gt;
        ///  &lt;/WorkPlace&gt;
        ///  &lt;WorkPlace&gt;
        ///    &lt;m_Name&gt;018 Xfone&lt;/m_Name&gt;
        ///  &lt;/WorkPlace&gt;
        ///  &lt;WorkPlace&gt;
        ///    &lt;m_Name&gt;10beats&lt;/m_Name&gt;
        ///  &lt;/WorkPlace&gt;
        ///  &lt;WorkPlace&gt;
        ///    &lt;m_Name&gt;10x.org.il&lt;/m_Name&gt;
        ///  &lt;/WorkPlace&gt;
        ///  &lt;WorkPlace&gt;
        ///    &lt;m_Name&gt;12 Wizards&lt;/m_Name&gt;
        ///  &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string israeliHitechList {
            get {
                return ResourceManager.GetString("israeliHitechList", resourceCulture);
            }
        }
    }
}
